baseURL = 'https://apuntes-isi.github.io/frre/'
languageCode = 'en-us'
title = 'Apuntes ISI FRRe'
theme = 'compose'

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]